name: Upload file to S3

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload index.html to S3
      run: |
        aws s3 cp file-upload/src/main/resources/static/index.html s3://${{ secrets.BUCKET_NAME }}/test/index.html
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
    - name: Notify Slack with File URL
      run: |
        FILE_URL="https://s3.${{ env.AWS_REGION }}.amazonaws.com/${{ secrets.BUCKET_NAME }}/test/index.html"
        curl -X POST -H 'Content-type: application/json' --data '{"text":"New File has been uploaded to: \n'$FILE_URL'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Notify Build Status to Slack.
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author,action,eventName,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}